### ISSUE TITLE
Handle both tagged AND untagged Cose_Sign1 objects

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/ValidationCore#5] opened 2021-05-04 06:29 UTC
I received some comments from developers that had been looking at your solution that you can't handle when the Cose_Sign1 isn't tagged. See my issue https://github.com/ehn-digital-green-development/hcert-spec/issues/69.

**Comment by asitdm** [comment] 2021-05-05 07:49
Duplicate of [https://github.com/ehn-digital-green-development/ValidationCore/issues/4](https://github.com/ehn-digital-green-development/ValidationCore/issues/4), see there.

**Closed by asitdm** 2021-05-05 07:49 UTC
